In [1]:
import time

import bs4
import pandas as pd
import requests
import numpy as np
import nltk
import matplotlib.pyplot as plt
import seaborn as sns
import gnews
import yfinance as yf
from gnews import GNews
from lxml.html.diff import href_token
import bs4 as bs
import json
import csv

In [2]:
news=GNews(start_date=(2019,11,4), end_date=(2024,11,2),max_results=1000)
ns=news.get_news("Microsoft")

C:\Users\Asus\anaconda3\Lib\site-packages\gnews\gnews.py:218: UserWarning: Only searches using get_news support date ranges. Start and end dates will be ignored.
  return self._get_news_more_than_100(key)

In [1]:
news_df=pd.DataFrame(data=ns)
news_df.head()

NameError: name 'pd' is not defined

In [4]:
news_df.shape

(1000, 5)

In [40]:
temp=news_df
temp["full_text"] = (temp["title"].fillna("") + "" +temp["description"].fillna(""))

In [41]:
temp.head()

,title,description,published date,url,publisher,full_text
0,Microsoft Bans Term ‘Microslop’ From Official ...,Microsoft Bans Term ‘Microslop’ From Official ...,"Mon, 02 Mar 2026 19:40:56 GMT",https://news.google.com/rss/articles/CBMikwFBV...,"{'href': 'https://gizmodo.com', 'title': 'Gizm...",Microsoft Bans Term ‘Microslop’ From Official ...
1,"Microsoft says stop calling it Microslop, or y...","Microsoft says stop calling it Microslop, or y...","Mon, 02 Mar 2026 15:35:00 GMT",https://news.google.com/rss/articles/CBMiowFBV...,"{'href': 'https://www.pcworld.com', 'title': '...","Microsoft says stop calling it Microslop, or y..."
2,Why the Microsoft 365 Copilot bug matters for ...,Why the Microsoft 365 Copilot bug matters for ...,"Mon, 02 Mar 2026 15:37:32 GMT",https://news.google.com/rss/articles/CBMihwFBV...,"{'href': 'https://www.foxnews.com', 'title': '...",Why the Microsoft 365 Copilot bug matters for ...
3,Microsoft ends data center non-disclosure agre...,Microsoft ends data center non-disclosure agre...,"Tue, 03 Mar 2026 19:22:00 GMT",https://news.google.com/rss/articles/CBMi6wFBV...,"{'href': 'https://www.detroitnews.com', 'title...",Microsoft ends data center non-disclosure agre...
4,Microsoft’s big developer conference returns t...,Microsoft’s big developer conference returns t...,"Tue, 03 Mar 2026 17:00:00 GMT",https://news.google.com/rss/articles/CBMiggFBV...,"{'href': 'https://www.theverge.com', 'title': ...",Microsoft’s big developer conference returns t...

In [48]:
temp.iloc[2,1]

'Why the Microsoft 365 Copilot bug matters for data security  Fox News'

In [8]:
news_df.to_csv(r"C:\Users\Asus\Documents\Skills\Python\Sentiment Analysis\MSFT_news.csv")

In [2]:
subreddit=["https://www.reddit.com/r/wallstreetbets/","https://www.reddit.com/r/stocks/"]

In [3]:
def scrape_reddit(subreddit:str,total_posts:int):

    all_data=[]         #main list
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"}     #framework

    for index,url in enumerate(subreddit):
        sr_name=url.split("/")[-2]      #names of subreddit
        after=None
        posts=[]
        print(sr_name)

        while len(all_data) < total_posts:

            params = {"limit": 100}
            if after:
                params["after"] = after

            try:
                response=requests.get(f"https://www.reddit.com/r/{sr_name}/.json",headers=headers,timeout=15,params=params)
                res_json=response.json()
                print(res_json)
                data = res_json["data"]["children"]
                response.raise_for_status()


                for post in data:
                    p = post["data"]
                    posts.append({"subreddit": sr_name,"title": p["title"],"url": "https://reddit.com" + p["permalink"],"score": p["score"],"num_comments": p["num_comments"],"created": p["created_utc"]})

                after = res_json["data"]["after"]

                if after is None:
                    break
                time.sleep(1)

                all_data.append(posts)


            except Exception as e:
                print(e)

    return all_data

def save_scraped_data(data, filename_json, filename_csv):
    if not data:
        print(f'No data')
        return


    try:
        with open(filename_json, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=2, ensure_ascii=True)
        print(f'Topics saved: {filename_json}')
    except Exception as e:
        print("ERROR:",e)



    try:
        with open(filename_csv, 'w', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow(['Subreddit', 'Type', 'Title', 'URL'])

            for subreddit_data in data:
                subreddit = subreddit_data['name']

                for topic in subreddit_data.get('topics', []):
                    writer.writerow([subreddit, topic['type'], topic['title'], ''])

                for discussion in subreddit_data.get('discussions', []):
                    writer.writerow([subreddit, discussion['type'], discussion['title'], discussion['url']])

            print(f'All topics saved to files!')
    except Exception as e:
        print("Error:",e)

In [4]:
a=scrape_reddit(subreddit,5)
a

[[{'subreddit': 'wallstreetbets',
   'title': 'Weekly Earnings Threads 3/2 - 3/6',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rgbpm8/weekly_earnings_threads_32_36/',
   'score': 192,
   'num_comments': 1236,
   'created': 1772210511.0},
  {'subreddit': 'wallstreetbets',
   'title': 'What Are Your Moves Tomorrow, March 06, 2026',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rltgpe/what_are_your_moves_tomorrow_march_06_2026/',
   'score': 169,
   'num_comments': 5158,
   'created': 1772744230.0},
  {'subreddit': 'wallstreetbets',
   'title': 'US grants waiver to allow India to buy Russian oil amid Iran war',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rm15iz/us_grants_waiver_to_allow_india_to_buy_russian/',
   'score': 1864,
   'num_comments': 160,
   'created': 1772762834.0},
  {'subreddit': 'wallstreetbets',
   'title': 'The market lately',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rlz6d2/the_market_lately/',
   'score': 1793,
   'num_comments': 103,
   'created': 1772757657.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Oracle Plans Thousands of Job Cuts in Face of AI Cash Crunch',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rlonra/oracle_plans_thousands_of_job_cuts_in_face_of_ai/',
   'score': 2155,
   'num_comments': 183,
   'created': 1772733782.0},
  {'subreddit': 'wallstreetbets',
   'title': 'US weighs oil futures market action to combat price spikes, White House official says',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rm01kq/us_weighs_oil_futures_market_action_to_combat/',
   'score': 415,
   'num_comments': 151,
   'created': 1772759885.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Why Is Insider Trading Allowed for Some People?',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rm5szj/why_is_insider_trading_allowed_for_some_people/',
   'score': 170,
   'num_comments': 49,
   'created': 1772776346.0},
  {'subreddit': 'wallstreetbets',
   'title': 'US Drafts Rules for Sweeping Power Over Nvidia’s Global Sales',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rloax2/us_drafts_rules_for_sweeping_power_over_nvidias/',
   'score': 1108,
   'num_comments': 206,
   'created': 1772733028.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Man, times really are tough out there.',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rl2nxa/man_times_really_are_tough_out_there/',
   'score': 44622,
   'num_comments': 2627,
   'created': 1772670381.0},
  {'subreddit': 'wallstreetbets',
   'title': 'FUCK PLTR',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rlnqt2/fuck_pltr/',
   'score': 480,
   'num_comments': 108,
   'created': 1772731821.0},
  {'subreddit': 'wallstreetbets',
   'title': 'OpenAI tops $25 billion in annualized revenue, The Information reports',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rldf5d/openai_tops_25_billion_in_annualized_revenue_the/',
   'score': 1373,
   'num_comments': 300,
   'created': 1772703776.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Finally made profit 😎',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rlufnl/finally_made_profit/',
   'score': 150,
   'num_comments': 32,
   'created': 1772746387.0},
  {'subreddit': 'wallstreetbets',
   'title': 'I Was a Broke Millennial. I Tried to Trade My Way to Financial Freedom.',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rm5lin/i_was_a_broke_millennial_i_tried_to_trade_my_way/',
   'score': 16,
   'num_comments': 24,
   'created': 1772775676.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Daily Discussion Thread for March 05, 2026',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rlfta1/daily_discussion_thread_for_march_05_2026/',
   'score': 265,
   'num_comments': 11430,
   'created': 1772712080.0},
  {'subreddit': 'wallstreetbets',
   'title': "Nvidia CEO Huang says $30 billion OpenAI investment 'might be the last'",
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkx43m/nvidia_ceo_huang_says_30_billion_openai/',
   'score': 3119,
   'num_comments': 233,
   'created': 1772657317.0},
  {'subreddit': 'wallstreetbets',
   'title': 'DHT Bull Case – Why the tanker market may be about to explode',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rlie0p/dht_bull_case_why_the_tanker_market_may_be_about/',
   'score': 125,
   'num_comments': 78,
   'created': 1772719309.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Someone fucking explain why Walmart ($WMT) is at 47x earnings?',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rl17jn/someone_fucking_explain_why_walmart_wmt_is_at_47x/',
   'score': 1294,
   'num_comments': 480,
   'created': 1772666746.0},
  {'subreddit': 'wallstreetbets',
   'title': 'ADBE is a War &amp; AI Play: Stock Pitch.PDF',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rm2o1h/adbe_is_a_war_ai_play_stock_pitchpdf/',
   'score': 6,
   'num_comments': 22,
   'created': 1772766916.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Dubai stock market crashes 4.6% at open.',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rke6hz/dubai_stock_market_crashes_46_at_open/',
   'score': 19953,
   'num_comments': 1022,
   'created': 1772605974.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Short btc wasn’t the move gang',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkp1s2/short_btc_wasnt_the_move_gang/',
   'score': 1908,
   'num_comments': 286,
   'created': 1772639612.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Broadcom +5% after-hours on Q1 2026 earnings beat. Revenue +29% YoY to $19.3B, AI +106% to $8.4B, guides $22B Q2 vs $20.6B est, $10B buyback',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rl47nl/broadcom_5_afterhours_on_q1_2026_earnings_beat/',
   'score': 289,
   'num_comments': 49,
   'created': 1772674492.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Vibes based investing',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rl5ij4/vibes_based_investing/',
   'score': 227,
   'num_comments': 35,
   'created': 1772678015.0},
  {'subreddit': 'wallstreetbets',
   'title': 'What Are Your Moves Tomorrow, March 05, 2026',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkxcve/what_are_your_moves_tomorrow_march_05_2026/',
   'score': 274,
   'num_comments': 7563,
   'created': 1772657871.0},
  {'subreddit': 'wallstreetbets',
   'title': 'ADP: Private employers added 63,000 jobs last in February, the best monthly showing since July',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rklpnx/adp_private_employers_added_63000_jobs_last_in/',
   'score': 877,
   'num_comments': 165,
   'created': 1772631651.0},
  {'subreddit': 'wallstreetbets',
   'title': 'MSFT slander no more',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkxlbb/msft_slander_no_more/',
   'score': 131,
   'num_comments': 44,
   'created': 1772658385.0},
  {'subreddit': 'wallstreetbets',
   'title': 'OPPA GANGNAM STYLE',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkrzu1/oppa_gangnam_style/',
   'score': 196,
   'num_comments': 72,
   'created': 1772646085.0},
  {'subreddit': 'wallstreetbets',
   'title': "South Korea's Kospi plunges 10% amid selloff in the region as Middle East war escalates",
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkaau5/south_koreas_kospi_plunges_10_amid_selloff_in_the/',
   'score': 2316,
   'num_comments': 267,
   'created': 1772593926.0},
  {'subreddit': 'wallstreetbets',
   'title': '$MDB $807---&gt;$7153',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkskxl/mdb_8077153/',
   'score': 101,
   'num_comments': 22,
   'created': 1772647325.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Daily Discussion Thread for March 04, 2026',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkjmj2/daily_discussion_thread_for_march_04_2026/',
   'score': 249,
   'num_comments': 10275,
   'created': 1772625681.0},
  {'subreddit': 'wallstreetbets',
   'title': "Here's some loss porn for you kinky fucks",
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkctew/heres_some_loss_porn_for_you_kinky_fucks/',
   'score': 607,
   'num_comments': 121,
   'created': 1772601446.0},
  {'subreddit': 'wallstreetbets',
   'title': 'A Lesson Regards Need In These Times',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjvrp1/a_lesson_regards_need_in_these_times/',
   'score': 4144,
   'num_comments': 135,
   'created': 1772559458.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Blacksky gain and a lesson learnt',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkqexd/blacksky_gain_and_a_lesson_learnt/',
   'score': 50,
   'num_comments': 28,
   'created': 1772642640.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Paramount (PSKY) Debt Downgraded to Junk Following Warner Bros. (WBD) Deal',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjns62/paramount_psky_debt_downgraded_to_junk_following/',
   'score': 10535,
   'num_comments': 618,
   'created': 1772540160.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Overnight puts until this thing is over',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rk48x4/overnight_puts_until_this_thing_is_over/',
   'score': 1225,
   'num_comments': 201,
   'created': 1772578226.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Turned 8k into 63k :]',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rk2ksk/turned_8k_into_63k/',
   'score': 1167,
   'num_comments': 142,
   'created': 1772574304.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Tomorrow: Trump Meets Amazon, Google, Microsoft, Meta, OpenAI &amp; xAI on AI Power Strategy',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjuncc/tomorrow_trump_meets_amazon_google_microsoft_meta/',
   'score': 1171,
   'num_comments': 231,
   'created': 1772557048.0},
  {'subreddit': 'wallstreetbets',
   'title': "Fed's Kashkari says Iran war obscures monetary policy outlook",
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjxvsc/feds_kashkari_says_iran_war_obscures_monetary/',
   'score': 717,
   'num_comments': 81,
   'created': 1772563956.0},
  {'subreddit': 'wallstreetbets',
   'title': 'The mf who bought GDX/GDXU Gold Miners on Friday',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjn8am/the_mf_who_bought_gdxgdxu_gold_miners_on_friday/',
   'score': 2475,
   'num_comments': 89,
   'created': 1772538419.0},
  {'subreddit': 'wallstreetbets',
   'title': '106k in spy puts, as jesus died for our sins i will die for your calls',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjnz6o/106k_in_spy_puts_as_jesus_died_for_our_sins_i/',
   'score': 1798,
   'num_comments': 168,
   'created': 1772540747.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Moderna +10% after-hours as Moderna agrees to pay up to $2.25B to settle COVID vaccine patent dispute',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rk2egk/moderna_10_afterhours_as_moderna_agrees_to_pay_up/',
   'score': 294,
   'num_comments': 32,
   'created': 1772573909.0},
  {'subreddit': 'wallstreetbets',
   'title': 'The valuation premium for the Mag7 ex $TSLA relative to the rest of the market just hit 2011 levels.',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjxyou/the_valuation_premium_for_the_mag7_ex_tsla/',
   'score': 436,
   'num_comments': 111,
   'created': 1772564138.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Back to Loss Porn',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rk2aqo/back_to_loss_porn/',
   'score': 225,
   'num_comments': 60,
   'created': 1772573675.0},
  {'subreddit': 'wallstreetbets',
   'title': 'What Are Your Moves Tomorrow, March 04, 2026',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rk1aji/what_are_your_moves_tomorrow_march_04_2026/',
   'score': 250,
   'num_comments': 9254,
   'created': 1772571432.0},
  {'subreddit': 'wallstreetbets',
   'title': "480k MU Guy (YOLO'ed 0DTE QQQ Calls, made a few thousand, reloaded back in)",
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjw8u5/480k_mu_guy_yoloed_0dte_qqq_calls_made_a_few/',
   'score': 377,
   'num_comments': 129,
   'created': 1772560482.0},
  {'subreddit': 'wallstreetbets',
   'title': 'EU Natural Gas is up +40% today',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjnvab/eu_natural_gas_is_up_40_today/',
   'score': 732,
   'num_comments': 195,
   'created': 1772540421.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Iran says Strait of Hormuz closed and warns it will attack ships trying to pass',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rj4gvm/iran_says_strait_of_hormuz_closed_and_warns_it/',
   'score': 18728,
   'num_comments': 1257,
   'created': 1772483900.0},
  {'subreddit': 'wallstreetbets',
   'title': '$31,000 EVER is looking Clear!',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rkcup9/31000_ever_is_looking_clear/',
   'score': 28,
   'num_comments': 13,
   'created': 1772601562.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Iran War $15,400 SPY Calls + $20,000 VIX Puts',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjzu7l/iran_war_15400_spy_calls_20000_vix_puts/',
   'score': 132,
   'num_comments': 67,
   'created': 1772568222.0},
  {'subreddit': 'wallstreetbets',
   'title': '$20k SPX Loss',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjxufj/20k_spx_loss/',
   'score': 126,
   'num_comments': 42,
   'created': 1772563871.0},
  {'subreddit': 'wallstreetbets',
   'title': 'I heard this is the sub where people YOLO into MU?',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjw65u/i_heard_this_is_the_sub_where_people_yolo_into_mu/',
   'score': 130,
   'num_comments': 48,
   'created': 1772560324.0},
  {'subreddit': 'wallstreetbets',
   'title': '$EVEX - Eve Air and its strong relationship with Embraer',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rk6i4j/evex_eve_air_and_its_strong_relationship_with/',
   'score': 35,
   'num_comments': 26,
   'created': 1772583778.0},
  {'subreddit': 'wallstreetbets',
   'title': 'S&amp;p 500 customer Put Delta position',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjmnn9/sp_500_customer_put_delta_position/',
   'score': 345,
   'num_comments': 79,
   'created': 1772536473.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Daily Discussion Thread for March 03, 2026',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjniae/daily_discussion_thread_for_march_03_2026/',
   'score': 304,
   'num_comments': 15374,
   'created': 1772539293.0},
  {'subreddit': 'wallstreetbets',
   'title': 'AVGO earnings play',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjx2mm/avgo_earnings_play/',
   'score': 58,
   'num_comments': 35,
   'created': 1772562225.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Back for seconds',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjv5p8/back_for_seconds/',
   'score': 58,
   'num_comments': 16,
   'created': 1772558147.0},
  {'subreddit': 'wallstreetbets',
   'title': '480k MU YOLO (240k in margin)',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjdoyx/480k_mu_yolo_240k_in_margin/',
   'score': 642,
   'num_comments': 306,
   'created': 1772506320.0},
  {'subreddit': 'wallstreetbets',
   'title': 'The mf who bought gold and crude oil x3 ETF on Friday',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rin5l8/the_mf_who_bought_gold_and_crude_oil_x3_etf_on/',
   'score': 13939,
   'num_comments': 442,
   'created': 1772439208.0},
  {'subreddit': 'wallstreetbets',
   'title': "The China Hustle 2.0 - How TikTok's Biggest Influencer Pumped &amp; Dumped His Fans... On The NASDAQ.",
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rj1mub/the_china_hustle_20_how_tiktoks_biggest/',
   'score': 1208,
   'num_comments': 130,
   'created': 1772477750.0},
  {'subreddit': 'wallstreetbets',
   'title': 'so many people will be obliterated by close',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rip2ap/so_many_people_will_be_obliterated_by_close/',
   'score': 5969,
   'num_comments': 306,
   'created': 1772446375.0},
  {'subreddit': 'wallstreetbets',
   'title': '$72000 Oil Calls 6DTE YOLO',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjipj7/72000_oil_calls_6dte_yolo/',
   'score': 94,
   'num_comments': 19,
   'created': 1772521781.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Nasdaq seeks SEC approval for prediction markets options on major stock index',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rix1yc/nasdaq_seeks_sec_approval_for_prediction_markets/',
   'score': 796,
   'num_comments': 117,
   'created': 1772468013.0},
  {'subreddit': 'wallstreetbets',
   'title': 'SPX 0dte 10 bagger speedrun (11min)',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjc0yw/spx_0dte_10_bagger_speedrun_11min/',
   'score': 130,
   'num_comments': 35,
   'created': 1772501879.0},
  {'subreddit': 'wallstreetbets',
   'title': 'What goes up must come down',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjiltn/what_goes_up_must_come_down/',
   'score': 45,
   'num_comments': 32,
   'created': 1772521413.0},
  {'subreddit': 'wallstreetbets',
   'title': 'What Are Your Moves Tomorrow, March 03, 2026',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rj4zuy/what_are_your_moves_tomorrow_march_03_2026/',
   'score': 244,
   'num_comments': 10083,
   'created': 1772485057.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Remember...',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rinq9k/remember/',
   'score': 1851,
   'num_comments': 42,
   'created': 1772441402.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Egg stock',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjg0z3/egg_stock/',
   'score': 41,
   'num_comments': 21,
   'created': 1772512906.0},
  {'subreddit': 'wallstreetbets',
   'title': '$30,000 SPY Put Yolo ⬆️date',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rizlkb/30000_spy_put_yolo_date/',
   'score': 318,
   'num_comments': 58,
   'created': 1772473436.0},
  {'subreddit': 'wallstreetbets',
   'title': 'Thank you big Yahu 🙏✌️',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rivrs1/thank_you_big_yahu/',
   'score': 456,
   'num_comments': 45,
   'created': 1772465188.0},
  {'subreddit': 'wallstreetbets',
   'title': '70x 685/687 call credit spreads expiring tomorrow. Great joy at the AH dump happening.',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjgty2/70x_685687_call_credit_spreads_expiring_tomorrow/',
   'score': 32,
   'num_comments': 20,
   'created': 1772515378.0},
  {'subreddit': 'wallstreetbets',
   'title': '3.5K USD in SPX gains today (3 PUTS, 1 Bear Call)',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rjaiau/35k_usd_in_spx_gains_today_3_puts_1_bear_call/',
   'score': 53,
   'num_comments': 12,
   'created': 1772497957.0},
  {'subreddit': 'wallstreetbets',
   'title': '$30k in ASTS stock',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1riueor/30k_in_asts_stock/',
   'score': 257,
   'num_comments': 74,
   'created': 1772462033.0},
  {'subreddit': 'wallstreetbets',
   'title': '"Is the market literally restarted? $35 Buyout vs $28 Market Price. 📉🤡"',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rj3er6/is_the_market_literally_restarted_35_buyout_vs_28/',
   'score': 94,
   'num_comments': 93,
   'created': 1772481576.0},
  {'subreddit': 'wallstreetbets',
   'title': '99k loan ATOM yolo',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rix92g/99k_loan_atom_yolo/',
   'score': 162,
   'num_comments': 129,
   'created': 1772468438.0},
  {'subreddit': 'wallstreetbets',
   'title': 'I just mogged myself 😂',
   'url': 'https://reddit.com/r/wallstreetbets/comments/1rj49ez/i_just_mogged_myself/',
   'score': 73,
   'num_comments': 49,
   'created': 1772483444.0},

In [6]:
save_scraped_data(a,"smth.json","smth.csv")

Topics saved: smth.json
Error: list indices must be integers or slices, not str

In [7]:
f=pd.read_json("smth.json")
f

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,"{'subreddit': 'wallstreetbets', 'title': 'Week...","{'subreddit': 'wallstreetbets', 'title': 'What...","{'subreddit': 'wallstreetbets', 'title': 'US g...","{'subreddit': 'wallstreetbets', 'title': 'The ...","{'subreddit': 'wallstreetbets', 'title': 'Orac...","{'subreddit': 'wallstreetbets', 'title': 'US w...","{'subreddit': 'wallstreetbets', 'title': 'Why ...","{'subreddit': 'wallstreetbets', 'title': 'US D...","{'subreddit': 'wallstreetbets', 'title': 'Man,...","{'subreddit': 'wallstreetbets', 'title': 'FUCK...",...,"{'subreddit': 'wallstreetbets', 'title': 'Mode...","{'subreddit': 'wallstreetbets', 'title': 'Am I...","{'subreddit': 'wallstreetbets', 'title': '32k ...","{'subreddit': 'wallstreetbets', 'title': 'some...","{'subreddit': 'wallstreetbets', 'title': 'Dail...","{'subreddit': 'wallstreetbets', 'title': 'Casi...","{'subreddit': 'wallstreetbets', 'title': 'Rega...","{'subreddit': 'wallstreetbets', 'title': 'Shop...","{'subreddit': 'wallstreetbets', 'title': 'I th...","{'subreddit': 'wallstreetbets', 'title': 'CVNA..."
1,"{'subreddit': 'wallstreetbets', 'title': 'Week...","{'subreddit': 'wallstreetbets', 'title': 'What...","{'subreddit': 'wallstreetbets', 'title': 'US g...","{'subreddit': 'wallstreetbets', 'title': 'The ...","{'subreddit': 'wallstreetbets', 'title': 'Orac...","{'subreddit': 'wallstreetbets', 'title': 'US w...","{'subreddit': 'wallstreetbets', 'title': 'Why ...","{'subreddit': 'wallstreetbets', 'title': 'US D...","{'subreddit': 'wallstreetbets', 'title': 'Man,...","{'subreddit': 'wallstreetbets', 'title': 'FUCK...",...,"{'subreddit': 'wallstreetbets', 'title': 'Mode...","{'subreddit': 'wallstreetbets', 'title': 'Am I...","{'subreddit': 'wallstreetbets', 'title': '32k ...","{'subreddit': 'wallstreetbets', 'title': 'some...","{'subreddit': 'wallstreetbets', 'title': 'Dail...","{'subreddit': 'wallstreetbets', 'title': 'Casi...","{'subreddit': 'wallstreetbets', 'title': 'Rega...","{'subreddit': 'wallstreetbets', 'title': 'Shop...","{'subreddit': 'wallstreetbets', 'title': 'I th...","{'subreddit': 'wallstreetbets', 'title': 'CVNA..."
2,"{'subreddit': 'wallstreetbets', 'title': 'Week...","{'subreddit': 'wallstreetbets', 'title': 'What...","{'subreddit': 'wallstreetbets', 'title': 'US g...","{'subreddit': 'wallstreetbets', 'title': 'The ...","{'subreddit': 'wallstreetbets', 'title': 'Orac...","{'subreddit': 'wallstreetbets', 'title': 'US w...","{'subreddit': 'wallstreetbets', 'title': 'Why ...","{'subreddit': 'wallstreetbets', 'title': 'US D...","{'subreddit': 'wallstreetbets', 'title': 'Man,...","{'subreddit': 'wallstreetbets', 'title': 'FUCK...",...,"{'subreddit': 'wallstreetbets', 'title': 'Mode...","{'subreddit': 'wallstreetbets', 'title': 'Am I...","{'subreddit': 'wallstreetbets', 'title': '32k ...","{'subreddit': 'wallstreetbets', 'title': 'some...","{'subreddit': 'wallstreetbets', 'title': 'Dail...","{'subreddit': 'wallstreetbets', 'title': 'Casi...","{'subreddit': 'wallstreetbets', 'title': 'Rega...","{'subreddit': 'wallstreetbets', 'title': 'Shop...","{'subreddit': 'wallstreetbets', 'title': 'I th...","{'subreddit': 'wallstreetbets', 'title': 'CVNA..."
3,"{'subreddit': 'wallstreetbets', 'title': 'Week...","{'subreddit': 'wallstreetbets', 'title': 'What...","{'subreddit': 'wallstreetbets', 'title': 'US g...","{'subreddit': 'wallstreetbets', 'title': 'The ...","{'subreddit': 'wallstreetbets', 'title': 'Orac...","{'subreddit': 'wallstreetbets', 'title': 'US w...","{'subreddit': 'wallstreetbets', 'title': 'Why ...","{'subreddit': 'wallstreetbets', 'title': 'US D...","{'subreddit': 'wallstreetbets', 'title': 'Man,...","{'subreddit': 'wallstreetbets', 'title': 'FUCK...",...,"{'subreddit': 'wallstreetbets', 'title': 'Mode...","{'subreddit': 'wallstreetbets', 'title': 'Am I...","{'subreddit': 'wallstreetbets', 'title': '32k ...","{'subreddit': 'wallstreetbets', 'title': 'some...","{'subreddit': 'wallstreetbets', 'title': 'Dail...","{'subreddit': 'wallstreetbets', 'title': 'Casi...","{'subreddit': 'wallstreetbets', 'title': 'Rega...","{'subreddit': 'wallstreetbets', 'title': 'Shop...","{'subreddit': 'wallstreetbets', 'title': 'I th...","{'subreddit': 'wallstreetbets', 'title': 'CVNA..."
4,"{'subreddit': 'wallstreetbets', 'title': 'Week...","{'subreddit': 'wallstreetbets', 'title': 'What...","{'subreddit': 'wallstreetbets', 'title': 'US g...","{'subreddit': 'wallstreetbets', 'title': 'The ...","{'subreddit': 'wallstreetbets', 'title': 'Orac...","{'subreddit': 'wallstreetbets', 'title': 'US w...","{'subreddit': 'wallstreetbets', 'title': 'Why ...","{'subreddit': 'wallstreetbets', 'title': 'US D...","{'subreddit': 'wallstreetbets', 'title': 'Man,...","{'subreddit': 'wallstreetbets', 'title': 'FUCK...",...,"{'subreddit': 'wallstreetbets', 'title': 'Mode...","{'subreddit': 'wallstreetbets', 'title': 'Am I...","{'subreddit': 'wallstreetbets', 'title': '32k ...","{'subreddit': 'wallstreetbets', 'title': 'some...","{'subreddit': 'wallstreetbets', 'title': 'Dail...","{'subreddit': 'wallstreetbets', 'title': 'Casi...","{'subreddit': 'wallstreetbets', 'title': 'Rega...","{'subreddit': 'wallstreetbets', 'title': 'Shop...","{'subreddit': 'wallstreetbets', 'title': 'I th...","{'subreddit': 'wallstreetbets', 'title': 'CVNA..."

In [22]:
def scrape_reddit(subreddit):
    all_data=[]
    for index,url in enumerate(subreddit):
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"}
        sr_name=url.split("/")[-2]
        print(sr_name)

        try:
            response=requests.get(url,headers=headers,timeout=15)
            response.raise_for_status()

            soup=bs4.BeautifulSoup(response.content,"html.parser")

            subreddit_data={"name":sr_name,"url":url,"title":soup.title.string if soup.title.string else "No Title"}


            topics=[]

            for heading in soup.find_all(['h1','h2','h3','h4']):
                text=heading.get_text(strip=True)

                if text and len(text)>3:
                    if any(keyword in text.lower() for keyword in ['rise','oil','bullish','stocks','bonds','tax','chips','luxury']):
                        topics.append({"title":text,"subreddit":sr_name,"type":"topic"})
            discussions=[]
            seen_url=set()

            for link in soup.find_all('a',href=True):
                text=link.get_text(strip=True)
                href=link['href']
                if text and len(text)>1 and ('/comments/' in href) and (href not in seen_url):
                    seen_url.add(href)
                    discussions.append({"title":text,"url":href,"type":"discussions"})

            subreddit_data["topic"]=topics
            subreddit_data["discussions"]=discussions


            all_data.append(subreddit_data)
            time.sleep(2)

        except Exception as e:
            print(e)

    return all_data

def save_scraped_data(data, filename_json, filename_csv):
    if not data:
        print(f'No data')
        return


    try:
        with open(filename_json, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=2, ensure_ascii=True)
        print(f'Topics saved: {filename_json}')
    except Exception as e:
        print("ERROR:",e)



    try:
        with open(filename_csv, 'w', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow(['Subreddit', 'Type', 'Title', 'URL'])

            for subreddit_data in data:
                subreddit = subreddit_data['name']

                for topic in subreddit_data.get('topics', []):
                    writer.writerow([subreddit, topic['type'], topic['title'], ''])

                for discussion in subreddit_data.get('discussions', []):
                    writer.writerow([subreddit, discussion['type'], discussion['title'], discussion['url']])

            print(f'All topics saved to files!')
    except Exception as e:
        print("Error:",e)

In [26]:
a=scrape_reddit(subreddit)
save_scraped_data(a,"smth.json","smth.csv")
a

[{'name': 'wallstreetbets',
  'url': 'https://www.reddit.com/r/wallstreetbets/',
  'title': 'Reddit - The heart of the internet',
  'topic': [],
  'discussions': [{'title': 'Weekly Earnings Threads 3/2 - 3/6votes •comments',
    'url': '/r/wallstreetbets/comments/1rgbpm8/weekly_earnings_threads_32_36/',
    'type': 'discussions'},
   {'title': 'What Are Your Moves Tomorrow, March 06, 2026',
    'url': '/r/wallstreetbets/comments/1rltgpe/what_are_your_moves_tomorrow_march_06_2026/',
    'type': 'discussions'},
   {'title': 'US grants waiver to allow India to buy Russian oil amid Iran war',
    'url': '/r/wallstreetbets/comments/1rm15iz/us_grants_waiver_to_allow_india_to_buy_russian/',
    'type': 'discussions'},
   {'title': 'Supreme Court rules that Trump’s sweeping emergency tariffs are illegal | CNN Politics',
    'url': '/r/wallstreetbets/comments/1r9xu7b/supreme_court_rules_that_trumps_sweeping/',
    'type': 'discussions'},
   {'title': 'The market lately',
    'url': '/r/wallstreetbets/comments/1rlz6d2/the_market_lately/',
    'type': 'discussions'}]},
 {'name': 'stocks',
  'url': 'https://www.reddit.com/r/stocks/',
  'title': 'Reddit - The heart of the internet',
  'topic': [{'title': 'r/stocks', 'subreddit': 'stocks', 'type': 'topic'},
   {'title': 'Rate My Portfolio - r/Stocks Quarterly Thread March 2026',
    'subreddit': 'stocks',
    'type': 'topic'},
   {'title': 'r/Stocks Daily Discussion & Options Trading Thursday - Mar 05, 2026',
    'subreddit': 'stocks',
    'type': 'topic'},
   {'title': 'r/stocks Rules', 'subreddit': 'stocks', 'type': 'topic'},
   {'title': 'No cryptocoin discussions unrelated to stocks',
    'subreddit': 'stocks',
    'type': 'topic'}],
  'discussions': [{'title': 'Rate My Portfolio - r/Stocks Quarterly Thread March 2026votes •comments',
    'url': '/r/stocks/comments/1rhtjtk/rate_my_portfolio_rstocks_quarterly_thread_march/',
    'type': 'discussions'},
   {'title': 'r/Stocks Daily Discussion & Options Trading Thursday - Mar 05, 2026votes •comments',
    'url': '/r/stocks/comments/1rle70j/rstocks_daily_discussion_options_trading_thursday/',
    'type': 'discussions'},
   {'title': "Trump on rising gas prices during Iran operation: 'If they rise, they rise'",
    'url': '/r/stocks/comments/1rlqxo4/trump_on_rising_gas_prices_during_iran_operation/',
    'type': 'discussions'},
   {'title': 'Trump’s Global Tariffs Struck Down by US Supreme Court',
    'url': '/r/stocks/comments/1r9xpm4/trumps_global_tariffs_struck_down_by_us_supreme/',
    'type': 'discussions'},
   {'title': 'Next stocks to be added to s and p 500 in rebalancing tomorrow',
    'url': '/r/stocks/comments/1rlt7xm/next_stocks_to_be_added_to_s_and_p_500_in/',
    'type': 'discussions'}]}]

In [27]:
path=(r"C:\Users\Asus\PycharmProjects\test_2\smth.csv")
scraped_df=pd.read_csv(path)
scraped_df

,Subreddit,Type,Title,URL
0,wallstreetbets,discussions,Weekly Earnings Threads 3/2 - 3/6votes •comments,/r/wallstreetbets/comments/1rgbpm8/weekly_earn...
1,wallstreetbets,discussions,"What Are Your Moves Tomorrow, March 06, 2026",/r/wallstreetbets/comments/1rltgpe/what_are_yo...
2,wallstreetbets,discussions,US grants waiver to allow India to buy Russian...,/r/wallstreetbets/comments/1rm15iz/us_grants_w...
3,wallstreetbets,discussions,Supreme Court rules that Trump’s sweeping emer...,/r/wallstreetbets/comments/1r9xu7b/supreme_cou...
4,wallstreetbets,discussions,The market lately,/r/wallstreetbets/comments/1rlz6d2/the_market_...
5,stocks,discussions,Rate My Portfolio - r/Stocks Quarterly Thread ...,/r/stocks/comments/1rhtjtk/rate_my_portfolio_r...
6,stocks,discussions,r/Stocks Daily Discussion & Options Trading Th...,/r/stocks/comments/1rle70j/rstocks_daily_discu...
7,stocks,discussions,Trump on rising gas prices during Iran operati...,/r/stocks/comments/1rlqxo4/trump_on_rising_gas...
8,stocks,discussions,Trump’s Global Tariffs Struck Down by US Supre...,/r/stocks/comments/1r9xpm4/trumps_global_tarif...
9,stocks,discussions,Next stocks to be added to s and p 500 in reba...,/r/stocks/comments/1rlt7xm/next_stocks_to_be_a...

In [31]:
scraped_df.iloc[2,2]

'US grants waiver to allow India to buy Russian oil amid Iran war'

In [49]:
all_data=[]         #main list
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"}     #framework

for index,url in enumerate(subreddit):
        sr_name="wallstreetbets"      #names of subreddit
        after=None
        posts=[]
        print(sr_name)
        params = {"limit": 100}
        if after:
                params["after"] = after

        try:
                response=requests.get(f"https://www.reddit.com/r/{sr_name}/.json",headers=headers,timeout=15,params=params)
                res_json=response.json()
                data = res_json["data"]["children"]
                response.raise_for_status()
                for post in data:
                    p = post["data"]

                    comment_url = "https://reddit.com" + p["permalink"] + ".json"

                    comment_response = requests.get(comment_url, headers=headers)
                    comment_json = comment_response.json()
                    comments = []

                    for c in comment_json[1]["data"]["children"]:
                        if c["kind"] == "t1":   # t1 = comment
                            comments.append(c["data"]["body"])

                    posts.append({"subreddit": sr_name,"title": p["title"],"url": "https://reddit.com" + p["permalink"],"score": p["score"],"num_comments": p["num_comments"],"comments": comments})



        except Exception as e:
            print(e)

Expecting value: line 1 column 1 (char 0)

In [4]:
def scrape_reddit(subreddit: list, total_posts: int):
    all_data = []  #main list
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"}  #framework

    for index, url in enumerate(subreddit):
        sr_name = url.split("/")[-2]  #names of subreddit
        after = None
        posts = []
        print(sr_name)

        while len(posts) < total_posts:

            params = {"limit": total_posts}
            #to check the loop may be taking 50 posts then is checking which is the stuff we want etc
            if after:
                params["after"] = after

            try:
                response = requests.get(f"https://www.reddit.com/r/{sr_name}/.json", headers=headers, timeout=15,
                                        params=params)
                res_json = response.json()
                data = res_json["data"]["children"]
                response.raise_for_status()

                for post in data:
                    p = post["data"]

                    comment_url = "https://reddit.com" + p["permalink"] + ".json"

                    comment_response = requests.get(comment_url, headers=headers)
                    comment_json = comment_response.json()
                    comments = []

                    for c in comment_json[1]["data"]["children"]:
                        time.sleep(0.5)
                        if c["kind"] == "t1":   # t1 = comment
                            comments.append(c["data"]["body"])

                    posts.append({"subreddit": sr_name,"title": p["title"],"url": "https://reddit.com" + p["permalink"],"score": p["score"],"num_comments": p["num_comments"],"comments": comments})


                after = res_json["data"]["after"]

                if after is None:
                    break
                time.sleep(1)

                all_data.extend(posts)


            except Exception as e:
                print(e)

    return all_data


def save_scraped_data(data, filename_json, filename_csv):
    if not data:
        print(f'No data')
        return

    try:
        with open(filename_json, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=2, ensure_ascii=True)
        print(f'Topics saved: {filename_json}')
    except Exception as e:
        print("ERROR:", e)

    try:
        with open(filename_csv, 'w', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow(['Subreddit', 'Type', 'Title', 'URL'])

            for subreddit_data in data:
                subreddit = subreddit_data['name']

                for topic in subreddit_data.get('topics', []):
                    writer.writerow([subreddit, topic['type'], topic['title'], ''])

                for discussion in subreddit_data.get('discussions', []):
                    writer.writerow([subreddit, discussion['type'], discussion['title'], discussion['url']])

            print(f'All topics saved to files!')
    except Exception as e:
        print("Error:", e)

In [5]:
a=scrape_reddit(subreddit,5)

stocks

In [6]:
a

[{'subreddit': 'wallstreetbets',
  'title': 'Weekly Earnings Threads 3/2 - 3/6',
  'url': 'https://reddit.com/r/wallstreetbets/comments/1rgbpm8/weekly_earnings_threads_32_36/',
  'score': 190,
  'num_comments': 1241,
  'comments': ['Competing against after hours institution news-based Bots that scan RSS feeds and wire services for specific keywords to trade on breaking news instantly.',
   '🥭 meeting with RTX and Lockheed tomorrow to “discuss weapons production”. ',
   'Petrobras 🤔🤔🤔',
   'Full ported gap puts, mrvl calls today',
   'Why is OMDA not moving on banger earnings?',
   'Fucking fuck MRVL shit. I bought calls past 2 earnings for them and got burned. Thought fuck this shit today and went puts. I’m bad at this',
   'Guidewire and pattern will also fly tomorrow.  they came thru with solid beats',
   '[deleted]',
   'Oh man mrvl had a triple beat and had pretty large beat for guidance. \n\nIts up so far, but it will drop 25% knowing this shithole market.\n\n I hope my $85 calls will print.',
   'Samsara not living up to its name. Too bad I was scared away because of the liquidity.',
   'samsara absolutely crushed it.  steak tonight.  no one mentioned this play.  thank you all again.',
   'Doesn’t look like there’ll be enough oomph on MRVL after you dumbasses were overpaying for the 1dte 90c at close',
   'gj talking me out of selling 20 puts on mrvl regards',
   'MRVL is back! ... to where it was last week',
   'You guys are cheering too early for MRVL',
   'So did MRVL win?',
   'and MRVL pumps! Congrats',
   "266% IV on IOT, show me some nice Theta decay u bitch. Pls don't tank like 20% thanks\n\nMRVL pumps! GG",
   'MRVL way too obvious so it’s gonna crater. or maybe that is obvious and therefore it will moon? fuuuuck',
   'yall go buy the dip on EONR\n\n',
   'MRVL 80C because my spidey senses are tingling\n\nor maybe that’s my new buttplug',
   'got 6 shares of costco for ER. #bigballa',
   'Imagine if COST increases the hot dog price we would be so fucked ',
   'Actually, changed my mind. Taking chances on GAP and MRVL puts.',
   'From what ppl are saying, Costco hardly ever moves on earnings. I’ll just buy tmr morning depending on the results',
   'Go pro calls since everyone is gonna want prime time war footage ',
   'how we feelin MRVL earnings?',
   'Wanna buy PBR just for the ticker symbol.',
   'I wanna sell 1 put on cost. Worth? ',
   'GAP calls cuz I bought a $40 hoodie 2 months ago. That should help in beating earnings 😎',
   'where do you guys find info regarding the earnings for each stock, like the previous earnings, price before earnings and after, and all that? ',
   'https://preview.redd.it/jod1nx85sang1.png?width=372&amp;format=png&amp;auto=webp&amp;s=e6dc046fb0cd4ab6fcedc77062f52e1faf0300a4',
   'petition to have mag7 have earnings once a month because all these other stocks are shit and boring as fuck ',
   'Mrvl calls? ',
   'what do we think about IOT?',
   'MRVL calls GAP puts and Costco flat',
   "anyone playing pattern for earnings?\n\nalso, is GoPro releasing after hours today or not?  i'm seeing conflicting info on it",
   'Welp I would skip Costco unless your theta gang. It’s already at max pain',
   'So if Marvell does well in earnings I kind of expect stuff life POET to jump a little too.  Too much hopeium there?',
   'Why do I feel like GWRE is gonna dump.',
   'looks like they got all of the exit liquidity on AEO yesterday to pull it back',
   '$GAP puts',
   'I had calls on Veeva, okta, pdyn, avgo.  ',
   'Aeo plz dump to 18',
   'I had AVGO and OKTA puts :(',
   'no on here mentioned / cared about PDYN when I brought it up yesterday.  Monster win yet again.  Thank you again for your silence.  gotta love sleeper plays.',
   'Came here to thank the “trust me” person who suggested puts on ANF and AEO… I still have the ANF puts.. but I screenshot the AEO puts.. good enough to post then..  almost a 13 percent move? I wasn’t going to wait on this one..\n\nhttps://preview.redd.it/qhrcehvxq8ng1.jpeg?width=1170&amp;format=pjpg&amp;auto=webp&amp;s=30e833204233fcf3071760c7b45abc3f5894455a',
   'COSTCO CALLS 🗣️',
   'This aeo dump is an extreme over reaction. Triple beat on top and bottom line. Much better sales of their new aeri brand. \n\nSo they are trying to nitpick on tariffs margin impact and the fact that revenues are going be higher in the second half of the year...... 13% dump.\n\nI feel like it will recover next week but my calls are kaput no matter what. Sweeney we could have been great together 💔',
   'MDB is alive! Rise my child! Calls at the bottom!',
   'Nice, AEO puts saved my port for the week. Gonna look for next week cause the rest looks like junk.',
   '$JD ***-92% EPS*** ☠️⚰️☠️⚰️☠️⚰️☠️\n\nRMB2.7B loss vs. RMB9.9B profit YoY \n\n*Never* buy Gynah!',
   'PDYN 🚀🚀🚀🚀🚀🚀🚀🚀',
   'Lets go Trmed🚀🔥',
   'lost 80% with a MONGO June call (LMAO wtf was that)\n\nty AVGO making it back',
   'AVGO up, QQQ down, why do I get deja vu from Nvidia earnings? Or am I a regard?',
   'Smells like AVGO pop on open if 340 breaks bruh all ya put holders are smoked. Tald ya\n\nSo funny with the logic "NVDA smashed historic gainz yet it went down" well duh it was near ATH and we didn\'t de-risk with macro war catalysts, like we did all those days before AVGO earnings.\n\nYou guys don\'t pay attention. Just watch pattern on similar stocks and make leveraged bets according to that? Lmao no wonder why MM\'s getting rich af',
   '$TTD CEO bought 148M worth of stock and just announced potential partnership with OpenAi for advertising ',
   'Lol AEO has 0 volume even during pre-market, guess no one gives a shit about this piece of shit',
   'Ooooh baby. My $12 AMPX calls going to put me way up. Great way to start March. ',
   'Played full port avgo calls, bull puts.\nHope they keep printing throughout the day',
   'go pro baby lets gooooo\n\n',
   'None of this shit matters. Thursday’s are always when it gaps or drills to fuck over call and put holders.\nOnly big dick and don’t give a fuck energy people will buy call/put expiring tomorrow. \n\nEveryone else sit at the cuck chair 🪑 ',
   'I’m so confused did AMPX report early?',
   'Dump truck Thursday. Fuck your calls',
   'GoPro looking super juicy here',
   'Gonna full port gopro',
   'Got smoked on american eagle and bull anyone elsep',
   'they gone and cracked my barrel',
   'I come here everyday because it’s impossible to find 4 million acoustic people anywhere else but this sub ',
   "AVGO puts could be the play at the open with another lackluster report like NVDA's.  Business is humming but expectations are through the roof so it's hard to pump."]},
 {'subreddit': 'wallstreetbets',
  'title': 'What Are Your Moves Tomorrow, March 06, 2026',
  'url': 'https://reddit.com/r/wallstreetbets/comments/1rltgpe/what_are_your_moves_tomorrow_march_06_2026/',
  'score': 184,
  'num_comments': 5802,
  'comments': ['What better way to end the week than getting fucked by theta ',
   'Turns out I might have inadvertently bought a war profiteer stock with my rubber plantation a couple of months ago. XD',
   "Hope y'all bought the dip",
   'Buying puts tmr morning 🦅🦅🦅🦅',
   'I’m going to ban myself from the sub for 12 hours. ✌️',
   'I came here and read looking for the meaning of the world and I have not found it',
   'It’s like they say: &gt;!if you weak spaghetti, you’ll mom’s knees.!&lt;',
   'Europe and Asia are green which means gay bers r fuk for the next 6 months',
   'My favorite part of Friday was how the indices and vix were both red. Totally cool and straight. 😮\u200d💨👌',
   'Beautiful all you can buy setup for Bull. ',
   'Why can’t we ban countries that dump overnight from our stock market? Wouldn’t that make number go up?',
   'Why is everyone shorting war gold?',
   'Everyone expecting sell off into weekend, which means inverse and we bull today. \n\nIf no societal collapse over weekend, we rip to new ATH next week. ',
   'i just gonna use isreal as usa market indicator now.\n\nif isreal red usa green , if israel green usa red.\n\nso far israel is still green.',
   'I\'m like "Hey, what\'s up? Hello"     \n',
   'Bearish sentiment in here this morning, y’all gonna lose your asses today smh',
   'Thanks for the dip buy europoors. lets take spy to 700 already',
   'I’m 500 shares of MU, just gotta convince myself to not run away with a loss and hold for another 2 weeks until earning. This clown show needs to disappear ',
   'Today is puts, fears what happens on the weekend',
   "Sigh. corn is still too high, the war is another regular sandwar, and it's leg day and my legs are too shaky to get food.\n\nSomeone send chicken nao plz",
   'Yours retarded pedo 🥭 drag random countries in the war \n\nAnd also how the fuck is possible retarded Barron is most successful trader? Why nobody talking about this shit when it’s obvious what’s going on \n\nUS market deserve to take big shit like really big shit\n\n\n',
   '!banbet TSLA 410 1d',
   'GOOGL 310 ',
   "Kind of wild how many ppl here who trade dont understand why Iran hasn't destroyed our market vs. Ukraine/Russia. Iran has been disconnected from our markets for decades via sanctions. Meaning we buy nothing from them.. like its illegal to. Ukraine/Russia we bought tons of stuff agricultural products, industrial products, various commodities etc. Pretty simple bro. Its not a conspiracy ",
   'Unh rocket ship today\n\nDividend play',
   'I just want world peace, ^and ^girls ^with ^fat ^bums',
   '[removed]',
   'Spy futes falling off a cliff',
   'I just want peace for the world, and money for me',
   '184,000 autists online on WSB monitoring the situation. ',
   'I hate feeling like the richest man alive after having 1 good week. Need to remember to stay humble and focused otherwise I’m gonna blow this again ',
   'Since LPG is a byproduct of crude oil production. Do we just buy shares in oil and crude oil producers now',
   'if they rise, they rise',
   'Crude 90 today? What we saying',
   'March is going to be bullish. We will rip off any good news and any dip caused by bad news will be bought up.\n\nThe real pain is going to begin April onwards when Big Tech starts reporting earnings again.',
   'Euro riches',
   "And it's gone",
   'How are yall feeling about the market for later today? Morning pump then trickle down red or just out the gate red?',
   'Im hoping for a nice and easy day trade. I don’t want to hold over the weekend ',
   "Gonna turn off notifications and spend the day playing Pokopia, regardless what position I take it'll end up red anyway so fuck it I'ma build me a cool village instead.",
   'Can we not dump every time overnight for once ',
   "This doesn't look too great bulls.",
   'Bond market getting yippy',
   '!banbet MU 480 30d',
   "STOXX 50 is still the most oversold out of NQ, S&amp;P500 and HSI. HSI rebounded 1.7% so that's nice.",
   'India invokes emergency powers, orders refiners to boost LPG output\nIndia has invoked emergency \u2060powers and directed \u2060refiners to maximise production of liquefied petroleum gas (LPG) to prevent a shortage of the cooking fuel after \u2060supply disruptions caused by the Middle East crisis, a government order showed.\n\nThe world’s second-biggest importer of LPG last \u2060year consumed 33.15 million metric tonnes of cooking gas, which is a mixture of propane and butane. Imports account for about two-thirds of LPG consumption, with the Middle East making up about \u200c85 to 90 percent of that supply.\n\nAll oil refiners are asked to “maximise and ensure that propane and butane available with them are utilized for production of LPG”, the order issued late on Thursday showed.\n\nThe country has about 332 million active LPG consumers, government data showed.\n\nReported by: Aljazeera',
   'OIL to 100+',
   'What are the odds on a “special operation” boots on the ground invasion after market close to clear out the old leadership and out before market open Monday? ',
   'How we feeling about this munition meeting',
   'I’m retarded. I’m also high as fuuuuq. 🤌',
   '[deleted]',
   'WHAT THA FAH DUDE ONLY ONE DOLLA UP ',
   'I love that some grain bulker just Leeroy Jenkinsd his ship through the strait and out.\n\nName of the ship was the Iron Maiden \n\nhttps://youtu.be/RvEw2WEUY_s\n\nhttps://www.marinetraffic.com/en/ais/details/ships/shipid:729643/mmsi:538010225/imo:9691149/vessel:IRON%20MAIDEN',
   'I need to be locked up, for murdering my portfolio several times',
   '!banbet MU 410 13h',
   'People who refer to passengers as PAX on Reddit 💀',
   'I went all in on oil futures this morning. Took a nice profit early then shorted for a quick dip. Thats when my phone died and i got wiped out. Feelsbad',
   'I genuinely have no idea where to put money for quick flips in shares or calls. It just keeps flipping from red to green every other day\n\nThis is gey ',
   'How do I stop paper handing winners like a little bitch',
   '$MDB really said rip to puts',
   'In the shadowy realm of Wall Street, I knelt before the Lord of Bears, seeking wisdom on my portfolio. "O mighty one, shall I buy or sell?" I pleaded. With a thunderous roar, he uttered one word: "Red." And thus, my 401k became a ketchup factory.',
   '**yuropoors…** 😡',
   'I cant believe more people arent bearish; \n\nOn a superficial level we just had a look above and fail of Wednesday’s high.  \n\nOn a deeper level we have negative a:d with a suppressed trin. Put call ratio is elevated but falling.  Almanac leans bearish (but take that with a grain of salt).  \n\n6900 is the new 7000.  If we can just get to 6900, all our problems will be solved.   \n\nNot saying we definitely go down, but probability is not good.',
   'Bears are punching the air rn. Only things guaranteed in life is death, taxes, and the V',
   'Flairpours are disgusting 🧐',
   '!banbet SPY 690 13h',
   '#I’m autismtic',
   'so what do we think happens this weekend? Maybe US invades Taiwan',
   'Biggest Bull trap of 2026.',
   'CRWV is going to rip today',
   '#&gt;!🫲🅱️ENIS🫱!&lt;',
   'Am I winning yet?',
   'My phone died today while i was trading futures and i got fucked. Timing was good too. Sucks dude. ',
   '!banbet SNDK -6% 1d',
   'Tshina stocks back on the menu boys',
   'Its quiet... toooo quiet.',
   'Shorting war gold still the best play?',
   'Oil has broken out of the cage folks. Brent is showing positive on the exchange ',
   'This morning on our walk my dog found a yellow piece of ice some bitch in heat had gone number one on so he laid down and started licking it like a piss lollipop. That’s almost a human level of gooning',
   'LEAST EMOTIONAL TRADER WAITING FOR NFP 🤡🤡🤡',
   'We buying the new IPO for tomorrow? ',
   '.',
   'My pick.\n\nIs either.\n\nA. Energy crisis dulls for the day. Stocks recover. Modestly  🦬\n\nOr\n\nB. War continues and oil. Revives itself from the current slump.  🐻\n\n_____________________________\n\nIm going 🐻',
   'We’re getting close to weekend shenanigans ',
   'So, strategically, a lot usually happens Friday. \n\nTherefore, bers r fuk.',
   '*Crowd waits quietly in suspense as I stare into the abyss. Several minutes pass without a word, then I turn back to them*\n\n“Friday will be green!”\n\n*the crowd erupts in celebration*',
   'Has trump leaked NFP numbers ',
   'Market got zero reason to go up and that’s good enough reason for it to do exactly that']},
 {'subreddit': 'wallstreetbets',
  'title': 'US grants waiver to allow India to buy Russian oil amid Iran war',
  'url': 'https://reddit.com/r/wallstreetbets/comments/1rm15iz/us_grants_waiver_to_allow_india_to_buy_russian/',
  'score': 2376,
  'num_comments': 200,
  'comments': ['\n**User Report**| | | |\n:--|:--|:--|:--\n**Total Submissions** | 10 | **First Seen In WSB** | 2 years ago\n**Total Comments** | 91 | **Previous Best DD** | \n**Account Age** | 5 years | | \n\n[**Join WSB Discord**](https://discord.gg/wsbverse)',
   'So US bombing Iran to let others buy Russian oil? ',
   'If their gonna do it anyways, may as well pretend you gave permission.\xa0\n\n\nThanks for upvotes and comments, love you retards.\xa0',
   'This is one of the weirder “US policing the world” things I’ve heard. ',
   'I need a US goverment corruption ETF... i will YOLO it will go up forever ',
   'What waiver, 5 Russian tankers were already rerouted and enroute to India as of yesterday and 2 days ago.',
   'The US policing who buys who’s oil? What are we the mafia?',
   'Fucking 🌮',
   "There was news on Monday that India was already talking to Russia to start getting energy shipments, i don't think they would've cared for waivers if it was choosing between having ridiculously expensive oil vs discounted Russian oil.",
   "So the oil is only bad if it doesn't pass through a specific set of paperwork first? Good to know. ",
   "So that was what 2 Scaramucci's? Barely even that. ",
   'There is a saying spit and lick, exactly what he is trying to do now. ',
   'Almost as if you bully a country for decades, fund their enemies, set up lopsided trade deals and then another country comes to their rescue, the bullied country is going to support the country that saved them in their time of need.',
   'And.....so it begins. \nThis is how the trump regime begins to allow Russia to make money. \nShould have seen it coming. ',
   'The US thinks it can dictate and counties should follow it. Guess what, India was always buying oil from Russia. It never stopped. So not sure what this guy or the US is smoking.',
   '😂😂😂 holy shit!! This administration is shameless and embarrassing!!',
   'Does this mean that if India went on the open market they would drive up prices for everyone?  Where is all this oil that the US is producing?',
   'hahhahahaha they were going to do it anyway. this admin has no spine',
   'Well ya you dont wanna tarnish that safe heaven ',
   'The US allows India?  Is India not a sovereign country?',
   'All these guys are Russian assets and to pretend they aren’t is such bullshit',
   'Yup, further propping up his Russian Allies so that they can profit from our voluntary disruption of global Oil supply.',
   'India has always been close with Russia for years. \nIt’ll be interesting to see what happens to India when AI takes over their big outsource business.',
   'Since you all let us torpedo a completely peaceful demo boat and slaughter a bunch of Iranians you can now buy oil from this other place ',
   'Anything to fuck with Canada and help Russia.',
   'May I use the bathroom? ',
   'The real pain will come when they eventually change from th US dollar per barrel oil sale collapses.. Our one and only hold on the world.. buckle up..\n\nThe us dollar standard on oil trade..',
   'I say puts\xa0',
   'Leaps on China ',
   'Sometimes you gotta just ride the wave!!',
   'Dude they never stopped lol like do you not know the point of BRICS, its to stop using dollars for trade ',
   'Indian has been buying Russian oil for a while now ...like ....a long while. \n\nThis is meaningless ',
   'Is that his GRINDR profile pic? ',
   'bricks will be a little tuffer to break now ehh boys ',
   "It's become embarrassing ",
   'Wow. Just when I was thinking of granting a waiver to allow US bombing Iran',
   "Maybe we'll give China permission next 🤔",
   "Imagine how great the golden age will be once all of 🥭's 4D chess moves come together.\n\n/s",
   "crazy how a country needs another country's permission to buy another country's oil",
   'Did they ever stop buying lol?',
   'Winning!!',
   'Difficult to have to cater for Israel and Russia’s demands at the same time, but Donald found a way. Good job!',
   'So does this devalue oil stocks? ',
   'It’s hilarious we can grant a waiver for that.  How fucking cocky and smug we are.  ',
   'It’s weird India needs permission from US to buy oil.',
   'India has been buying 1 million barrels of Russian  oil per day. There are no sanctions literally who asked U.S ?',

In [8]:
a_df=pd.DataFrame(a)
a_df.iloc[1,5]

['What better way to end the week than getting fucked by theta ',
 'Turns out I might have inadvertently bought a war profiteer stock with my rubber plantation a couple of months ago. XD',
 "Hope y'all bought the dip",
 'Buying puts tmr morning 🦅🦅🦅🦅',
 'I’m going to ban myself from the sub for 12 hours. ✌️',
 'I came here and read looking for the meaning of the world and I have not found it',
 'It’s like they say: &gt;!if you weak spaghetti, you’ll mom’s knees.!&lt;',
 'Europe and Asia are green which means gay bers r fuk for the next 6 months',
 'My favorite part of Friday was how the indices and vix were both red. Totally cool and straight. 😮\u200d💨👌',
 'Beautiful all you can buy setup for Bull. ',
 'Why can’t we ban countries that dump overnight from our stock market? Wouldn’t that make number go up?',
 'Why is everyone shorting war gold?',
 'Everyone expecting sell off into weekend, which means inverse and we bull today. \n\nIf no societal collapse over weekend, we rip to new ATH next week. ',
 'i just gonna use isreal as usa market indicator now.\n\nif isreal red usa green , if israel green usa red.\n\nso far israel is still green.',
 'I\'m like "Hey, what\'s up? Hello"     \n',
 'Bearish sentiment in here this morning, y’all gonna lose your asses today smh',
 'Thanks for the dip buy europoors. lets take spy to 700 already',
 'I’m 500 shares of MU, just gotta convince myself to not run away with a loss and hold for another 2 weeks until earning. This clown show needs to disappear ',
 'Today is puts, fears what happens on the weekend',
 "Sigh. corn is still too high, the war is another regular sandwar, and it's leg day and my legs are too shaky to get food.\n\nSomeone send chicken nao plz",
 'Yours retarded pedo 🥭 drag random countries in the war \n\nAnd also how the fuck is possible retarded Barron is most successful trader? Why nobody talking about this shit when it’s obvious what’s going on \n\nUS market deserve to take big shit like really big shit\n\n\n',
 '!banbet TSLA 410 1d',
 'GOOGL 310 ',
 "Kind of wild how many ppl here who trade dont understand why Iran hasn't destroyed our market vs. Ukraine/Russia. Iran has been disconnected from our markets for decades via sanctions. Meaning we buy nothing from them.. like its illegal to. Ukraine/Russia we bought tons of stuff agricultural products, industrial products, various commodities etc. Pretty simple bro. Its not a conspiracy ",
 'Unh rocket ship today\n\nDividend play',
 'I just want world peace, ^and ^girls ^with ^fat ^bums',
 '[removed]',
 'Spy futes falling off a cliff',
 'I just want peace for the world, and money for me',
 '184,000 autists online on WSB monitoring the situation. ',
 'I hate feeling like the richest man alive after having 1 good week. Need to remember to stay humble and focused otherwise I’m gonna blow this again ',
 'Since LPG is a byproduct of crude oil production. Do we just buy shares in oil and crude oil producers now',
 'if they rise, they rise',
 'Crude 90 today? What we saying',
 'March is going to be bullish. We will rip off any good news and any dip caused by bad news will be bought up.\n\nThe real pain is going to begin April onwards when Big Tech starts reporting earnings again.',
 'Euro riches',
 "And it's gone",
 'How are yall feeling about the market for later today? Morning pump then trickle down red or just out the gate red?',
 'Im hoping for a nice and easy day trade. I don’t want to hold over the weekend ',
 "Gonna turn off notifications and spend the day playing Pokopia, regardless what position I take it'll end up red anyway so fuck it I'ma build me a cool village instead.",
 'Can we not dump every time overnight for once ',
 "This doesn't look too great bulls.",
 'Bond market getting yippy',
 '!banbet MU 480 30d',
 "STOXX 50 is still the most oversold out of NQ, S&amp;P500 and HSI. HSI rebounded 1.7% so that's nice.",
 'India invokes emergency powers, orders refiners to boost LPG output\nIndia has invoked emergency \u2060powers and directed \u2060refiners to maximise production of liquefied petroleum gas (LPG) to prevent a shortage of the cooking fuel after \u2060supply disruptions caused by the Middle East crisis, a government order showed.\n\nThe world’s second-biggest importer of LPG last \u2060year consumed 33.15 million metric tonnes of cooking gas, which is a mixture of propane and butane. Imports account for about two-thirds of LPG consumption, with the Middle East making up about \u200c85 to 90 percent of that supply.\n\nAll oil refiners are asked to “maximise and ensure that propane and butane available with them are utilized for production of LPG”, the order issued late on Thursday showed.\n\nThe country has about 332 million active LPG consumers, government data showed.\n\nReported by: Aljazeera',
 'OIL to 100+',
 'What are the odds on a “special operation” boots on the ground invasion after market close to clear out the old leadership and out before market open Monday? ',
 'How we feeling about this munition meeting',
 'I’m retarded. I’m also high as fuuuuq. 🤌',
 '[deleted]',
 'WHAT THA FAH DUDE ONLY ONE DOLLA UP ',
 'I love that some grain bulker just Leeroy Jenkinsd his ship through the strait and out.\n\nName of the ship was the Iron Maiden \n\nhttps://youtu.be/RvEw2WEUY_s\n\nhttps://www.marinetraffic.com/en/ais/details/ships/shipid:729643/mmsi:538010225/imo:9691149/vessel:IRON%20MAIDEN',
 'I need to be locked up, for murdering my portfolio several times',
 '!banbet MU 410 13h',
 'People who refer to passengers as PAX on Reddit 💀',
 'I went all in on oil futures this morning. Took a nice profit early then shorted for a quick dip. Thats when my phone died and i got wiped out. Feelsbad',
 'I genuinely have no idea where to put money for quick flips in shares or calls. It just keeps flipping from red to green every other day\n\nThis is gey ',
 'How do I stop paper handing winners like a little bitch',
 '$MDB really said rip to puts',
 'In the shadowy realm of Wall Street, I knelt before the Lord of Bears, seeking wisdom on my portfolio. "O mighty one, shall I buy or sell?" I pleaded. With a thunderous roar, he uttered one word: "Red." And thus, my 401k became a ketchup factory.',
 '**yuropoors…** 😡',
 'I cant believe more people arent bearish; \n\nOn a superficial level we just had a look above and fail of Wednesday’s high.  \n\nOn a deeper level we have negative a:d with a suppressed trin. Put call ratio is elevated but falling.  Almanac leans bearish (but take that with a grain of salt).  \n\n6900 is the new 7000.  If we can just get to 6900, all our problems will be solved.   \n\nNot saying we definitely go down, but probability is not good.',
 'Bears are punching the air rn. Only things guaranteed in life is death, taxes, and the V',
 'Flairpours are disgusting 🧐',
 '!banbet SPY 690 13h',
 '#I’m autismtic',
 'so what do we think happens this weekend? Maybe US invades Taiwan',
 'Biggest Bull trap of 2026.',
 'CRWV is going to rip today',
 '#&gt;!🫲🅱️ENIS🫱!&lt;',
 'Am I winning yet?',
 'My phone died today while i was trading futures and i got fucked. Timing was good too. Sucks dude. ',
 '!banbet SNDK -6% 1d',
 'Tshina stocks back on the menu boys',
 'Its quiet... toooo quiet.',
 'Shorting war gold still the best play?',
 'Oil has broken out of the cage folks. Brent is showing positive on the exchange ',
 'This morning on our walk my dog found a yellow piece of ice some bitch in heat had gone number one on so he laid down and started licking it like a piss lollipop. That’s almost a human level of gooning',
 'LEAST EMOTIONAL TRADER WAITING FOR NFP 🤡🤡🤡',
 'We buying the new IPO for tomorrow? ',
 '.',
 'My pick.\n\nIs either.\n\nA. Energy crisis dulls for the day. Stocks recover. Modestly  🦬\n\nOr\n\nB. War continues and oil. Revives itself from the current slump.  🐻\n\n_____________________________\n\nIm going 🐻',
 'We’re getting close to weekend shenanigans ',
 'So, strategically, a lot usually happens Friday. \n\nTherefore, bers r fuk.',
 '*Crowd waits quietly in suspense as I stare into the abyss. Several minutes pass without a word, then I turn back to them*\n\n“Friday will be green!”\n\n*the crowd erupts in celebration*',
 'Has trump leaked NFP numbers ',
 'Market got zero reason to go up and that’s good enough reason for it to do exactly that']

In [9]:
a_df.to_csv(r"C:\Users\Asus\PycharmProjects\test_2\smth.csv")

In [ ]:
#soup.prettify makes html look like normal

#soup.find('<h1,h2,h5,div>') gives that tag line it gives first occurence of h5 soup.find_all('<h5>') gives all occurences
#tags=soup.find_all('<h5>')
#for i in tags:
#   i.text gives text values

#fs=soup.find_all('div',class_='card') {class_ here _ is important as class is a keyword in python}
#for i in fs:
#   i.<'h5','h1'> will give h5 tages or h1 tags
#   i.h5.text gives text
#   i.a